### PR TITLE
Remove usage of `kubectl` provisioner

### PR DESCRIPTION
**Pull request by lawliet89**
To-do
- configure kubectl provider

### CODE REVIEW

**Comment by lawliet89** [comment]
@gowripadmajas Removing usage of the `kubectl` provisioner here.

**Review by niroz89 — APPROVED** [review]
LGTM

**Comment by niroz89** [comment]
@lawliet89 above `TO-DO` is not needed right ?

**Comment by lawliet89** [comment]
Hmm yea. I'll remove the providers separately and document it.

**Comment by niroz89** [comment]
once this is released, I will switch back the hashicorp/tfc-agent, revert this PR https://github.com/SPHTech/sph-aws-infra/pull/181

**Comment by niroz89** [comment]
@lawliet89 I was following the provider issue on this, shall we implement using kubernetes annotation ( https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations ) ? so there is no need of kubectl provider.

https://github.com/hashicorp/terraform-provider-kubernetes/issues/723#issuecomment-1141833527

**Comment by lawliet89** [comment]
Yes. This is new. I'll swap it over.

**Review by niroz89 — APPROVED** [review]
Thank you @lawliet89

**Pull request merged**
